version: '3.8'

services:

  database:
    container_name: database
    ports:
      - "5432:5432"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database-data:/var/lib/postgresql/data
    networks:
      mynetwork:

  back:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    container_name: back
    ports:
      - '3000:3000'
    depends_on:
      - database
    volumes:
      - ./backend:/app
    networks:
      - mynetwork

  front:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    container_name: front
    ports:
      - '3001:3001'
    depends_on:
      - back
    volumes:
      - ./frontend:/app
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork